export const WEB_KYP_GET_USERS = 'WEB_KYP_GET_USERS';
export const EXAMPLES_FETCH_USER_LIST_SUCCESS = 'EXAMPLES_FETCH_USER_LIST_SUCCESS';
export const EXAMPLES_FETCH_USER_LIST_FAILURE = 'EXAMPLES_FETCH_USER_LIST_FAILURE';
export const WEB_KYP_GET_WOODS = 'WEB_KYP_GET_WOODS';
export const EXAMPLES_FETCH_WOODS_LIST_SUCCESS = 'EXAMPLES_FETCH_WOODS_LIST_SUCCESS';
export const EXAMPLES_FETCH_WOODS_LIST_FAILURE = 'EXAMPLES_FETCH_WOODS_LIST_FAILURE';
export const WEB_KYP_SEND_ORDER = 'WEB_KYP_SEND_ORDER';
export const WEB_KYP_CREATE_ORDER = 'WEB_KYP_CREATE_ORDER';
